files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%language%/%original_file_name%
  - source: app/src/obf/res/values/strings.xml
    translation: app/src/obf/res/values-%language%/%original_file_name%
  - source: app/src/off/res/values/strings.xml
    translation: app/src/obf/res/values-%language%/%original_file_name%
