files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
  - source: /app/src/obf/res/values/strings.xml
    translation: /app/src/obf/res/values-%android_code%/%original_file_name%
  - source: /app/src/off/res/values/strings.xml
    translation: /app/src/off/res/values-%android_code%/%original_file_name%
  - source: /app/src/opff/res/values/strings.xml
    translation: /app/src/opff/res/values-%android_code%/strings.xml
