language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
  licenses:
    - 'android-sdk-.*'
    - '.*intel.+'
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

install:
  - ./gradlew assembleDebug --stacktrace

branches:
  only:
    - master

env:
  global:
    - TRAVIS=true
    - ADB_INSTALL_TIMEOUT=8
  matrix:
    # - ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a
    # - ANDROID_TARGET=android-17 ANDROID_ABI=armeabi-v7a
    # - ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a
    # - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    # - ANDROID_TARGET=android-20 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    # - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
addons:
  code_climate:
    repo_token: 2b24c9463329705e25db1b4ed139d9eb32a9cc36160f848ecb936579f94670b0

notifications:
  email: false

sudo: false